import './globals.css'
import type { Metadata } from "next";
import { getDevice } from "@/utils/getdevice";
import { PropsWithChildren } from "react";
import Footer from "./components/Footer";
import Header from "./components/Header";
import MainLinkSection from "./components/Header/MainLinkSection";
import SideLinkSection from "./components/Header/SideLinkSection";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
};

export default function RootLayout({ children }: PropsWithChildren) {
  const device = getDevice();
  return (
    <html lang="ko">
      <body className="overflow-x-hidden">
        {" "}
        <Header />
        {device === "pc" && <MainLinkSection />}
        {device === "mobile" && <SideLinkSection />}
        {children}
        <Footer />
      </body>
    </html>
  );
}


